# SPDX-FileCopyrightText: 2023 Ludger Sandig <sandig@statistik.tu-dortmund.de>
# SPDX-License-Identifier: CC0-1.0

whitespace_ops_in_indices=true
remove_extra_newlines=true
format_docstrings=true
trailing_comma=true
separate_kwargs_with_semicolon=false
surround_whereop_typeparameters=false
always_for_in=true